version: '2'

services:
  mongodb:
    image: docker.io/bitnami/mongodb:5.0
    container_name: $MONGODB_CONTAINER_NAME
    restart: always
    env_file:
      - .env
    ports:
      - 9999:27017

volumes:
  data:
    driver: local
