version: '3'
services:
  mongo:
    image: mongo
    container_name: database
    restart: always
    env_file:
      - .env

  mongo-express:
    image: mongo-express
    container_name: database-gui
    restart: always
    ports:
      - 8081:8081
    env_file:
      - .env
